// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StarWarsAPI.Data;

#nullable disable

namespace StarWarsAPI.Migrations
{
    [DbContext(typeof(StarWarsContext))]
    partial class StarWarsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StarWarsAPI.Models.Entities.Habitant", b =>
                {
                    b.Property<int>("IdHabitant")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdHabitant");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdHabitant"));

                    b.Property<int>("IdHomePlanet")
                        .HasColumnType("int")
                        .HasColumnName("IdHomePlanet");

                    b.Property<int>("IdSpecies")
                        .HasColumnType("int")
                        .HasColumnName("IdSpecies");

                    b.Property<bool>("IsRebel")
                        .HasColumnType("bit")
                        .HasColumnName("IsRebel");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NameHabitant");

                    b.HasKey("IdHabitant");

                    b.ToTable("Habitants");
                });

            modelBuilder.Entity("StarWarsAPI.Models.Entities.Planet", b =>
                {
                    b.Property<int>("IdPlanet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdPlanet");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPlanet"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NamePlanet");

                    b.HasKey("IdPlanet");

                    b.ToTable("Planets");
                });

            modelBuilder.Entity("StarWarsAPI.Models.Entities.Species", b =>
                {
                    b.Property<int>("IdSpecies")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdSpecies");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSpecies"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NameSpecies");

                    b.HasKey("IdSpecies");

                    b.ToTable("Species");
                });
#pragma warning restore 612, 618
        }
    }
}
