// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StarWarsAPI.Data;

#nullable disable

namespace StarWarsAPI.Migrations
{
    [DbContext(typeof(StarWarsContext))]
    partial class StarWarsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StarWarsAPI.Models.Habitant", b =>
                {
                    b.Property<int>("IdHabitant")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDHABITANT");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdHabitant"));

                    b.Property<int>("IdHomePlanet")
                        .HasColumnType("int")
                        .HasColumnName("IDHOMEPLANET");

                    b.Property<int>("IdSpecies")
                        .HasColumnType("int")
                        .HasColumnName("IDSPECIES");

                    b.Property<bool>("IsRebel")
                        .HasColumnType("bit")
                        .HasColumnName("ISREBEL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NAMEHABITANT");

                    b.HasKey("IdHabitant");

                    b.ToTable("HABITANTS");
                });

            modelBuilder.Entity("StarWarsAPI.Models.Planet", b =>
                {
                    b.Property<int>("IdPlanet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDPLANET");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPlanet"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NAMEPLANET");

                    b.HasKey("IdPlanet");

                    b.ToTable("PLANETS");
                });

            modelBuilder.Entity("StarWarsAPI.Models.Species", b =>
                {
                    b.Property<int>("IdSpecies")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDSPECIES");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSpecies"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NAMESPECIES");

                    b.HasKey("IdSpecies");

                    b.ToTable("SPECIES");
                });
#pragma warning restore 612, 618
        }
    }
}
