CREATE TABLE SPECIES
(
	IDSPECIES INT PRIMARY KEY,
	NAMESPECIES NVARCHAR(100) NOT NULL
);

CREATE TABLE PLANETS
(
	IDPLANET INT PRIMARY KEY,
	NAMEPLANET NVARCHAR(100) NOT NULL
);

CREATE TABLE HABITANTS
(
	IDHABITANT INT PRIMARY KEY,
	NAMEHABITANT NVARCHAR(100) NOT NULL,
	IDSPECIES INT NOT NULL,
	IDHOMEPLANET INT NOT NULL,
	ISREBEL BIT NOT NULL,
	CONSTRAINT FK_SPECIES FOREIGN KEY (IDSPECIES) REFERENCES SPECIES(IDSPECIES) ON DELETE CASCADE,
	CONSTRAINT FK_HOMEPLANET FOREIGN KEY (IDHOMEPLANET) REFERENCES PLANETS(IDPLANET) ON DELETE CASCADE
);

INSERT INTO SPECIES VALUES (1, 'Human');
INSERT INTO SPECIES VALUES (2, 'Wookiee');
INSERT INTO SPECIES VALUES (3, 'Twilek');
INSERT INTO SPECIES VALUES (4, 'Droid');

INSERT INTO PLANETS VALUES (1, 'Tatooine');
INSERT INTO PLANETS VALUES (2, 'Kashyyyk');
INSERT INTO PLANETS VALUES (3, 'Ryloth');
INSERT INTO PLANETS VALUES (4, 'Coruscant');

INSERT INTO HABITANTS (IDHABITANT, NAMEHABITANT, IDSPECIES, IDHOMEPLANET, ISREBEL) VALUES (1, 'Luke Skywalker', 1, 1, 1);
INSERT INTO HABITANTS VALUES (2, 'Chewbacca', 2, 2, 1);
INSERT INTO HABITANTS VALUES (3, 'Aayla Secura', 3, 3, 1);
INSERT INTO HABITANTS VALUES (4, 'C-3PO', 4, 4, 0);
INSERT INTO HABITANTS VALUES (5, 'Leia Organa', 1, 4, 1);
